/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMobil.java
 *
 * Created on 02 Jun 12, 23:08:25
 */
package Forms;

import cls.ClassDB;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author riko
 */
public class FrmMobil extends javax.swing.JInternalFrame {

    /** Creates new form FrmMobil */
    public FrmMobil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TxtNoMesin = new javax.swing.JTextField();
        TxtTypeMobil = new javax.swing.JTextField();
        TxtWarnaMobil = new javax.swing.JTextField();
        TxtNoRangka = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtTahunPembuatan = new javax.swing.JTextField();
        TxtKodeMobil = new javax.swing.JTextField();
        TxtHargaSewa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtStatus = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("ENTRY DATA MOBIL");

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));
        jPanel2.setName("jPanel2"); // NOI18N

        TxtNoMesin.setName("TxtNoMesin"); // NOI18N

        TxtTypeMobil.setName("TxtTypeMobil"); // NOI18N

        TxtWarnaMobil.setName("TxtWarnaMobil"); // NOI18N

        TxtNoRangka.setName("TxtNoRangka"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("No. Rangka");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Type Mobil");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kode Mobil");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Harga Sewa");
        jLabel10.setName("jLabel10"); // NOI18N

        TxtTahunPembuatan.setName("TxtTahunPembuatan"); // NOI18N

        TxtKodeMobil.setName("TxtKodeMobil"); // NOI18N
        TxtKodeMobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtKodeMobilKeyPressed(evt);
            }
        });

        TxtHargaSewa.setName("TxtHargaSewa"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Warna Mobil");
        jLabel8.setName("jLabel8"); // NOI18N

        TxtStatus.setEditable(false);
        TxtStatus.setName("TxtStatus"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Status");
        jLabel9.setName("jLabel9"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setName("jPanel1"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_edit.png"))); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/diskette.png"))); // NOI18N
        jButton2.setText("SAVE");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_delete.png"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_warning.png"))); // NOI18N
        jButton4.setText("CANCEL");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        jButton5.setText("EXIT");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("No. Mesin");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tahun Pembuatan");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("EQUIZAKI CAR RENTAL");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Jl. Soekarno Hatta No.9, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141");
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtKodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTypeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNoMesin, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNoRangka, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtWarnaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtKodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(TxtTypeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtNoMesin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtNoRangka, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(TxtWarnaMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtTahunPembuatan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(TxtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    String kd=this.TxtKodeMobil.getText();
    String tm=this.TxtTypeMobil.getText();
    String nm=this.TxtNoMesin.getText();
    String nr=this.TxtNoRangka.getText();
    String wm=this.TxtWarnaMobil.getText();
    String tp=this.TxtTahunPembuatan.getText();
    String hs=this.TxtHargaSewa.getText();
    String st="Free";
    if("".equals(this.TxtKodeMobil.getText()) || ("".equals(this.TxtTypeMobil.getText())) || ("".equals(this.TxtNoMesin.getText())) || ("".equals(this.TxtNoRangka.getText())) || ("".equals(this.TxtWarnaMobil.getText())) || ("".equals(this.TxtTahunPembuatan.getText())))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi data");
        }else{
    try {        
      
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Insert into tblmobil values (?,?,?,?,?,?,?,?)";
            
            
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            p.setString(2, tm);  
            p.setString(3, nm);
            p.setString(4, nr);
            p.setString(5, wm);
            p.setString(6, tp);
            p.setString(7, hs);
            p.setString(8, st);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan " + e);
        }finally{
            HapusTeks();
    } 
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        String kd=this.TxtKodeMobil.getText();
        String tm=this.TxtTypeMobil.getText();
        String nm=this.TxtNoMesin.getText();
        String nr=this.TxtNoRangka.getText();
        String wm=this.TxtWarnaMobil.getText();
        String tp=this.TxtTahunPembuatan.getText();
        String hs=this.TxtHargaSewa.getText();
       
        if("".equals(this.TxtKodeMobil.getText()) || ("".equals(this.TxtTypeMobil.getText())) || ("".equals(this.TxtNoMesin.getText())) || ("".equals(this.TxtNoRangka.getText())) || ("".equals(this.TxtWarnaMobil.getText())) || ("".equals(this.TxtTahunPembuatan.getText())))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi data");
        }else{
    try {        
      
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Update tblmobil Set type_mobil=?,no_mesin=?,no_rangka=?,warna_mobil=?,thn_pemb=?,hrg_sewa=? Where kd_mobil=?";
            ResultSet r=s.executeQuery(sql);
            
           
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(7, kd);
            p.setString(1, tm);  
            p.setString(2, nm);
            p.setString(3, nr);
            p.setString(4, wm);
            p.setString(5, tp);
            p.setString(6, hs);
            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Edit data");
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }finally{
            HapusTeks();
    } 
        }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    String kd=this.TxtKodeMobil.getText();
    if("".equals(this.TxtKodeMobil.getText()) || ("".equals(this.TxtTypeMobil.getText())) || ("".equals(this.TxtNoMesin.getText())) || ("".equals(this.TxtNoRangka.getText())) || ("".equals(this.TxtWarnaMobil.getText())) || ("".equals(this.TxtTahunPembuatan.getText())))
        {
            JOptionPane.showMessageDialog(this, "Lengkapi data");
        }else{
    try {
            Connection c=ClassDB.getkoneksi();
            String sql = "DELETE From tblmobil  WHERE kd_mobil=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Hapus data");
        }catch(SQLException e){
            System.out.println("Terjadi kesalahan");
        }finally{
            HapusTeks();
        }
        }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    HapusTeks();
}//GEN-LAST:event_jButton4ActionPerformed
private void HapusTeks()
{
    this.TxtKodeMobil.setText(null);
    this.TxtHargaSewa.setText(null);
    this.TxtNoMesin.setText(null);
    this.TxtNoRangka.setText(null);
    this.TxtStatus.setText(null);
    this.TxtTahunPembuatan.setText(null);
    this.TxtTypeMobil.setText(null);
    this.TxtWarnaMobil.setText(null);
}

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
       this.dispose();
}//GEN-LAST:event_jButton5ActionPerformed

private void TxtKodeMobilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodeMobilKeyPressed
// TODO add your handling code here:
    try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblmobil where kd_mobil='" + this.TxtKodeMobil.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
           while (r.next()){
                this.TxtTypeMobil.setText(r.getString("type_mobil"));
                this.TxtHargaSewa.setText(r.getString("hrg_sewa"));
                this.TxtNoMesin.setText(r.getString("no_mesin"));
                this.TxtNoRangka.setText(r.getString("no_rangka"));
                this.TxtStatus.setText(r.getString("status"));
                this.TxtTahunPembuatan.setText(r.getString("thn_pemb"));
                this.TxtWarnaMobil.setText(r.getString("warna_mobil"));
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
}//GEN-LAST:event_TxtKodeMobilKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHargaSewa;
    private javax.swing.JTextField TxtKodeMobil;
    private javax.swing.JTextField TxtNoMesin;
    private javax.swing.JTextField TxtNoRangka;
    private javax.swing.JTextField TxtStatus;
    private javax.swing.JTextField TxtTahunPembuatan;
    private javax.swing.JTextField TxtTypeMobil;
    private javax.swing.JTextField TxtWarnaMobil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
