/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmTransPinjam.java
 *
 * Created on 03 Jun 12, 0:32:45
 */
package Forms;
import cls.ClassDB;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
/**
 *
 * @author riko
 */
public class FrmTransPinjam extends javax.swing.JInternalFrame {
private DefaultTableModel model;
    /** Creates new form FrmTransPinjam */
    public FrmTransPinjam() {
        initComponents();
        loadcombodata();
        model=new DefaultTableModel();
        tblPinjam.setModel(model);
        model.addColumn("Kode Peminjaman");
        model.addColumn("Kode Mobil");
        model.addColumn("Harga");  
        loadData();
        
    }
public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblPeminjamandetail where kd_pinjam='" + this.TxtKodePeminjaman.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o=new Object[3];
                o[0]=r.getString("kd_pinjam");
                o[1]=r.getString("kd_mobil");               
                o[2]=r.getString("harga");
                
                
                model.addRow(o);
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }    
public void loadcombodata(){
    try {        
        TxtIDPeminjam.removeAllItems();
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select ID_Peminjam from tblpeminjam group by id_peminjam";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtIDPeminjam.addItem(r.getString("ID_Peminjam"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }
    
    try {        
        TxtKodeMobil.removeAllItems();
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select kd_mobil from tblmobil Where status='Free' group by kd_mobil";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtKodeMobil.addItem(r.getString("kd_mobil"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        } 
    
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtIDPeminjam = new javax.swing.JComboBox();
        TxtNamaPeminjam = new javax.swing.JTextField();
        TxtTglPinjam = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        TxtJamPinjam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TxtKodeMobil = new javax.swing.JComboBox();
        TxtTipeMobil = new javax.swing.JTextField();
        TxtHargaSewa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        TxtTglKembali = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        TxtJamKembali = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtLamaSewa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtDP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtSisa = new javax.swing.JTextField();
        TxtKodePeminjaman = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        setTitle("ENTRY PEMINJAMAN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("EQUIZAKI CAR RENTAL");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Jl. Soekarno Hatta No.9, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kode Peminjaman");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Peminjam");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nama Peminjaman");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Kode Mobil");
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Type Mobil");
        jLabel8.setName("jLabel8"); // NOI18N

        TxtIDPeminjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtIDPeminjam.setName("TxtIDPeminjam"); // NOI18N
        TxtIDPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDPeminjamActionPerformed(evt);
            }
        });

        TxtNamaPeminjam.setEditable(false);
        TxtNamaPeminjam.setName("TxtNamaPeminjam"); // NOI18N

        TxtTglPinjam.setName("TxtTglPinjam"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Jam");
        jLabel9.setName("jLabel9"); // NOI18N

        TxtJamPinjam.setName("TxtJamPinjam"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("(jam)");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Harga Sewa");
        jLabel11.setName("jLabel11"); // NOI18N

        TxtKodeMobil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtKodeMobil.setName("TxtKodeMobil"); // NOI18N
        TxtKodeMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeMobilActionPerformed(evt);
            }
        });

        TxtTipeMobil.setEditable(false);
        TxtTipeMobil.setName("TxtTipeMobil"); // NOI18N

        TxtHargaSewa.setEditable(false);
        TxtHargaSewa.setName("TxtHargaSewa"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPinjam.setName("tblPinjam"); // NOI18N
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjam);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tanggal Kembali");
        jLabel12.setName("jLabel12"); // NOI18N

        TxtTglKembali.setName("TxtTglKembali"); // NOI18N
        TxtTglKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTglKembaliMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtTglKembaliMouseExited(evt);
            }
        });
        TxtTglKembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTglKembaliKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Jam");
        jLabel13.setName("jLabel13"); // NOI18N

        TxtJamKembali.setName("TxtJamKembali"); // NOI18N
        TxtJamKembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtJamKembaliKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Lama Sewa");
        jLabel14.setName("jLabel14"); // NOI18N

        TxtLamaSewa.setEditable(false);
        TxtLamaSewa.setName("TxtLamaSewa"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("DP / Uang Muka");
        jLabel15.setName("jLabel15"); // NOI18N

        TxtDP.setName("TxtDP"); // NOI18N
        TxtDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDPActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("TOTAL");
        jLabel16.setName("jLabel16"); // NOI18N

        TxtTotal.setEditable(false);
        TxtTotal.setName("TxtTotal"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Sisa Pembayaran");
        jLabel17.setName("jLabel17"); // NOI18N

        TxtSisa.setEditable(false);
        TxtSisa.setName("TxtSisa"); // NOI18N

        TxtKodePeminjaman.setName("TxtKodePeminjaman"); // NOI18N
        TxtKodePeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtKodePeminjamanMouseClicked(evt);
            }
        });
        TxtKodePeminjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtKodePeminjamanKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("jam");
        jLabel18.setName("jLabel18"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoppingcart_add.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/shoppingcart_remove.png"))); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/diskette.png"))); // NOI18N
        jButton3.setText("SAVE");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_edit.png"))); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_warning.png"))); // NOI18N
        jButton5.setText("CANCEL");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_delete.png"))); // NOI18N
        jButton6.setText("DELETE");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        jButton7.setText("EXIT");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(807, 807, 807))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(4, 4, 4)
                .addComponent(TxtJamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(794, 794, 794))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel3))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(TxtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(TxtJamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel10)
                                                    .addGap(135, 135, 135))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(TxtKodePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtIDPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(TxtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtKodeMobil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel8)
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel11))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(TxtTipeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(TxtHargaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(28, 28, 28)
                                        .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtDP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtKodePeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNamaPeminjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(TxtIDPeminjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(TxtJamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                    .addComponent(TxtTglPinjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(TxtTipeMobil)
                                                .addComponent(TxtHargaSewa))
                                            .addComponent(TxtKodeMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtTglKembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(TxtJamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel14)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtDP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TxtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TxtIDPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDPeminjamActionPerformed
// TODO add your handling code here:
    int i=TxtIDPeminjam.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtIDPeminjam.getSelectedItem();
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from tblpeminjam WHERE id_peminjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtNamaPeminjam.setText(result.getString("nama"));           
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtIDPeminjamActionPerformed

private void TxtKodeMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeMobilActionPerformed
// TODO add your handling code here:
    int i=TxtKodeMobil.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtKodeMobil.getSelectedItem();
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from tblMobil WHERE kd_mobil=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtTipeMobil.setText(result.getString("type_mobil"));           
            this.TxtHargaSewa.setText(result.getString("hrg_sewa"));           
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtKodeMobilActionPerformed

private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
// TODO add your handling code here:
    int i=tblPinjam.getSelectedRow();
        
        if(i==-1)
        {
            return;
        }
        String kode=(String) model.getValueAt(i, 0);        
               
        String kodebar=(String) model.getValueAt(i, 2);
        String jml=(String) model.getValueAt(i, 4);
        
        String sql1="Update barang Set stok=stok + ? where kd_barang=?";
        String sql="Delete from penjualan where no_transaksi=? AND kd_barang=?";
    try {        
    Connection c=ClassDB.getkoneksi();            
            PreparedStatement st=(PreparedStatement) c.prepareStatement(sql1);
            st.setString(1, jml);
            st.setString(2, kodebar);
            st.executeUpdate();
            st.close();
            
            PreparedStatement st2=(PreparedStatement) c.prepareStatement(sql);
            st2.setString(1, kode);
            st2.setString(2, kodebar);
            st2.executeUpdate();
            st2.close();
            
    }catch(SQLException e) {
        System.out.println(e);
    }finally{
        loadData();
    }
}//GEN-LAST:event_tblPinjamMouseClicked

private void TxtKodePeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtKodePeminjamanMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_TxtKodePeminjamanMouseClicked

private void TxtKodePeminjamanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKodePeminjamanKeyPressed
// TODO add your handling code here:
    
    loadData();
    try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblPeminjaman where kd_pinjam='" + this.TxtKodePeminjaman.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
                this.TxtIDPeminjam.setSelectedItem(r.getString("id_peminjam"));
            this.TxtTglPinjam.setDate(r.getDate("tgl_pinjam"));
            this.TxtTglKembali.setDate(r.getDate("tgl_hrs_kembali"));
            this.TxtJamPinjam.setText(r.getString("jam_p"));
            this.TxtJamKembali.setText(r.getString("jam_k"));
            this.TxtLamaSewa.setText(r.getString("lama_sewa"));
            this.TxtDP.setText(r.getString("dp"));
            this.TxtSisa.setText(r.getString("sisa_p"));
            
            r.close();
            s.close();
            }
            
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan " + e);
        }
    hitungtotal();
}//GEN-LAST:event_TxtKodePeminjamanKeyPressed

private void HapusTeks()
{
    this.TxtIDPeminjam.setSelectedItem(null);
            this.TxtKodePeminjaman.setText(null);
            
            this.TxtJamKembali.setText(null);
            this.TxtJamPinjam.setText(null);
            this.TxtLamaSewa.setText(null);
            this.TxtDP.setText(null);
            this.TxtSisa.setText(null);
            loadData();
}
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    String kode=this.TxtKodePeminjaman.getText();
   

    String KodeBar=(String) this.TxtKodeMobil.getSelectedItem();
    String Harga=this.TxtHargaSewa.getText();
   
        try {
            String sql1="Select * from tblpeminjamandetail where kd_pinjam='" + kode + "' AND kd_mobil='" + KodeBar + "'";
            Connection c=ClassDB.getkoneksi();            
            PreparedStatement st=(PreparedStatement) c.prepareStatement(sql1);
            ResultSet rs=st.executeQuery(sql1);
            if (rs.next())
            {
                
            JOptionPane.showMessageDialog(this, "Sudah ada");
            
            }else{
                String sql = "Insert into tblpeminjamandetail values (?,?,?)";
                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
                p.setString(1, kode);
                p.setString(2, KodeBar);
                
                p.setString(3, Harga);                        
                
                p.executeUpdate();
                p.close();
                this.updatemobil( KodeBar);
            
            }
        }catch(SQLException e){
            System.out.println(e);
        }finally{
            loadData();
            hitungtotal();
        }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    int i=tblPinjam.getSelectedRow();
        
        if(i==-1)
        {
            return;
        }
        String kode=(String) model.getValueAt(i, 0);        
               
        String kodebar=(String) model.getValueAt(i, 1);
        
        
        String sql1="Update tblmobil Set status='Free' where kd_mobil=?";
      
        String sql="Delete from tblpeminjamandetail where kd_pinjam=? AND kd_mobil=?";
        
    try {        
    Connection c=ClassDB.getkoneksi();      
            PreparedStatement st=(PreparedStatement) c.prepareStatement(sql1);
            
            st.setString(1, kodebar);
            st.executeUpdate();
            st.close();
            
            PreparedStatement st2=(PreparedStatement) c.prepareStatement(sql);
            st2.setString(1, kode);
            st2.setString(2, kodebar);
            st2.executeUpdate();
            st2.close();
            
    }catch(SQLException e) {
        System.out.println(e);
    }finally{
        loadData();
        hitungtotal();
    }
}//GEN-LAST:event_jButton2ActionPerformed

private void TxtJamKembaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJamKembaliKeyPressed
// TODO add your handling code here:
    hitunglama();
}//GEN-LAST:event_TxtJamKembaliKeyPressed

private void TxtTglKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTglKembaliMouseClicked
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtTglKembaliMouseClicked

private void TxtTglKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTglKembaliMouseExited
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtTglKembaliMouseExited

private void TxtTglKembaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTglKembaliKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtTglKembaliKeyPressed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    String kode=this.TxtKodePeminjaman.getText();
    String id_pinjam=(String) this.TxtIDPeminjam.getSelectedItem();
    java.util.Date tgl_pinjam=(java.util.Date) this.TxtTglPinjam.getDate();
    java.util.Date tgl_h_kembali=(java.util.Date) this.TxtTglKembali.getDate();
    String lama=this.TxtLamaSewa.getText();
    String jam_p=this.TxtJamPinjam.getText();
    String jam_k=this.TxtJamKembali.getText();
    String dp=this.TxtDP.getText();
    String sisa_p=this.TxtSisa.getText();
    
    if("".equals(this.TxtKodePeminjaman.getText()) || "".equals(this.TxtNamaPeminjam.getText()))
    {
       JOptionPane.showMessageDialog(this, "Lengkapi data");
    }else{
        try {
            Connection c=ClassDB.getkoneksi();
            String sql = "Insert into tblpeminjaman values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kode);            
            p.setString(2, id_pinjam);
            p.setDate(3, new java.sql.Date(tgl_pinjam.getTime()));            
            p.setDate(4, new java.sql.Date(tgl_h_kembali.getTime()));
            p.setString(5, lama);
            p.setString(6, jam_p);
            p.setString(7, jam_k);
            p.setString(8, dp);
            p.setString(9, sisa_p);
            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Tambah data");
            HapusTeks();
        }catch(SQLException e){
            System.out.println("Terjadi kesalahan");
        }
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    String kode=this.TxtKodePeminjaman.getText();
    String id_pinjam=(String) this.TxtIDPeminjam.getSelectedItem();
    java.util.Date tgl_pinjam=(java.util.Date) this.TxtTglPinjam.getDate();
    java.util.Date tgl_h_kembali=(java.util.Date) this.TxtTglKembali.getDate();
    String lama=this.TxtLamaSewa.getText();
    String jam_p=this.TxtJamPinjam.getText();
    String jam_k=this.TxtJamKembali.getText();
    String dp=this.TxtDP.getText();
    String sisa_p=this.TxtSisa.getText();
    
    if("".equals(this.TxtKodePeminjaman.getText()) || "".equals(this.TxtNamaPeminjam.getText()))
    {
       JOptionPane.showMessageDialog(this, "Lengkapi data");
    }else{
        try {
            Connection c=ClassDB.getkoneksi();
            String sql = "Update tblpeminjaman Set id_peminjam=?,tgl_pinjam=?,tgl_hrs_kembali=?,lama_sewa=?,jam_p=?,jam_k=?,dp=?,sisa_p=? Where kd_pinjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(9, kode);            
            p.setString(1, id_pinjam);
            p.setDate(2, new java.sql.Date(tgl_pinjam.getTime()));            
            p.setDate(3, new java.sql.Date(tgl_h_kembali.getTime()));
            p.setString(4, lama);
            p.setString(5, jam_p);
            p.setString(6, jam_k);
            p.setString(7, dp);
            p.setString(8, sisa_p);
            
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Sukses Update data");
        }catch(SQLException e){
            System.out.println("Terjadi kesalahan");
        }
    }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    try {        
        
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select kd_mobil from tblpeminjamandetail";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Connection c2=ClassDB.getkoneksi();
                
                String sql2="Update tblmobil Set status='Free' where tblmobil.kd_mobil=(Select kd_mobil from tblpeminjamandetail where tblpeminjamandetail.kd_mobil='" + r.getString("kd_mobil") + "')";
                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql2);
                p.executeUpdate();
                
                String sql3="Delete from tblpeminjamandetail where kd_mobil='" + r.getString("kd_mobil") + "'";
                PreparedStatement p2=(PreparedStatement) c.prepareStatement(sql3);            
                p2.executeUpdate();

            }
            r.close();
            s.close();
                
            String sql4="Delete from tblpeminjaman where kd_pinjam='" + this.TxtKodePeminjaman.getText() + "'";
                PreparedStatement p3=(PreparedStatement) c.prepareStatement(sql4);            
                p3.executeUpdate();
                
        }catch(SQLException e) {
            System.out.println(e);
        }
}//GEN-LAST:event_jButton6ActionPerformed

private void TxtDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDPActionPerformed
// TODO add your handling code here:
    DecimalFormat df = new DecimalFormat("#.##");
    double l=Double.valueOf(this.TxtTotal.getText());
    double m=Double.valueOf(this.TxtDP.getText());
    double lm=Double.valueOf(l-m);
    String lms=String.valueOf(lm);
    this.TxtSisa.setText(df.format(l-m));
}//GEN-LAST:event_TxtDPActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    HapusTeks();
    loadData();
}//GEN-LAST:event_jButton5ActionPerformed

private void hitungtotal()
{
    try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select sum(harga) as 'B' from tblPeminjamandetail where kd_pinjam='" + this.TxtKodePeminjaman.getText() + "'";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
            double h=Double.valueOf(r.getString("B"));
            double p=Double.valueOf(h);
            
            double c2=Double.valueOf(this.TxtLamaSewa.getText());
            DecimalFormat df = new DecimalFormat("#.##");
            double c3=Double.parseDouble(df.format(p*c2));
            String l=String.valueOf(c3);
            this.TxtTotal.setText(df.format(p*c2));
            }
            
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan " + e);
        }
}

private void updatemobil(String kdmobil)
{
    String sql1="Update tblmobil Set status='Loan' where kd_mobil=?";
    try {        
    Connection c=ClassDB.getkoneksi();            
            PreparedStatement st=(PreparedStatement) c.prepareStatement(sql1);
            st.setString(1, kdmobil);            
            
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
        System.out.println(e);
    }
}

private void hitunglama()
{       
    //Date d1 = new GregorianCalendar(this.TxtTglPinjam.getDate().getYear(), this.TxtTglPinjam.getDate().getMonth(), this.TxtTglPinjam.getDate().getDay(), 22, 59).getTime();
   // Date d2 = new GregorianCalendar(2012, 6, 3, 0, 59).getTime();
    //Date today = new Date();
    //long diff = d2.getTime() - d1.getTime();
   // JOptionPane.showMessageDialog(this, (diff / (1000 * 60 * 60 )));
    java.util.Date tgl1=(java.util.Date) this.TxtTglPinjam.getDate();
    java.util.Date tgl2=(java.util.Date) this.TxtTglKembali.getDate();
    long diff=((tgl2.getTime()- tgl1.getTime())/(1000 * 60 * 60 * 24));
    String a=(String.valueOf(diff));
    this.TxtLamaSewa.setText(a);
    hitungtotal();
    
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDP;
    private javax.swing.JTextField TxtHargaSewa;
    private javax.swing.JComboBox TxtIDPeminjam;
    private javax.swing.JTextField TxtJamKembali;
    private javax.swing.JTextField TxtJamPinjam;
    private javax.swing.JComboBox TxtKodeMobil;
    private javax.swing.JTextField TxtKodePeminjaman;
    private javax.swing.JTextField TxtLamaSewa;
    private javax.swing.JTextField TxtNamaPeminjam;
    private javax.swing.JTextField TxtSisa;
    private com.toedter.calendar.JDateChooser TxtTglKembali;
    private com.toedter.calendar.JDateChooser TxtTglPinjam;
    private javax.swing.JTextField TxtTipeMobil;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPinjam;
    // End of variables declaration//GEN-END:variables
}
