/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmTransPinjam.java
 *
 * Created on 03 Jun 12, 0:32:45
 */
package Forms;
import cls.ClassDB;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
/**
 *
 * @author riko
 */
public class FrmTransKembali extends javax.swing.JInternalFrame {
private DefaultTableModel model;
    /** Creates new form FrmTransPinjam */
    public FrmTransKembali() {
        initComponents();
        loadcombodata();
        model=new DefaultTableModel();
        tblPinjam.setModel(model);
        model.addColumn("Kode Peminjaman");
        model.addColumn("Kode Mobil");
        model.addColumn("Harga");  
        loadData();
        
    }
public void loadData() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblPeminjamandetail where kd_pinjam='" + this.TxtKodePeminjaman.getSelectedItem() + "'";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o=new Object[3];
                o[0]=r.getString("kd_pinjam");
                o[1]=r.getString("kd_mobil");               
                o[2]=r.getString("harga");
                
                
                model.addRow(o);
            }
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }
    }    
public void loadcombodata(){
    try {        
        TxtIDPeminjam.removeAllItems();
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select ID_Peminjam from tblpeminjam group by id_peminjam";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtIDPeminjam.addItem(r.getString("ID_Peminjam"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println(e);
        }
    try {        
        TxtKodePeminjaman.removeAllItems();
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblpeminjaman";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                TxtKodePeminjaman.addItem(r.getString("kd_pinjam"));
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        } 
  //  try {        
  //      TxtKodePeminjaman.removeAllItems();
        
   //         Connection c=ClassDB.getkoneksi();
   //         Statement s= c.createStatement();
   //         String sql="Select kd_pinjam from tblpeminjamandetail group by kd_pinjam";
    //        ResultSet r=s.executeQuery(sql);
            
     //       if(r.next())
     //       {
     //       while (r.next()) {
      //          TxtKodePeminjaman.addItem(r.getString("kd_pinjam"));
      //      }
      //      r.close();
      //      s.close();
      //      }
      //  }catch(SQLException e) {
      //      System.out.println(e);
      //  }
    //
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtIDPeminjam = new javax.swing.JComboBox();
        TxtNamaPeminjam = new javax.swing.JTextField();
        TxtTglPinjam = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        TxtJamPinjam = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPinjam = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        TxtTglKembali = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        TxtJamKembali = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtLamaSewa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TxtDP = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtSisa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        TxtKodeKembali = new javax.swing.JTextField();
        TxtKodePeminjaman = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        TxtDenda = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        TxtTglKembali1 = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        TxtTelatHari = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        TxtTelatJam = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TxtJamKembali3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TxtTotalBayar = new javax.swing.JTextField();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        setTitle("ENTRY PENGEMBALIAN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("EQUIZAKI CAR RENTAL");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Jl. Soekarno Hatta No.9, Jatimulyo, Kec. Lowokwaru, Kota Malang, Jawa Timur 65141");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kode Peminjaman");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Peminjam");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tanggal Pinjam");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nama Peminjaman");
        jLabel5.setName("jLabel5"); // NOI18N

        TxtIDPeminjam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtIDPeminjam.setName("TxtIDPeminjam"); // NOI18N
        TxtIDPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIDPeminjamActionPerformed(evt);
            }
        });

        TxtNamaPeminjam.setEditable(false);
        TxtNamaPeminjam.setName("TxtNamaPeminjam"); // NOI18N

        TxtTglPinjam.setName("TxtTglPinjam"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Jam");
        jLabel9.setName("jLabel9"); // NOI18N

        TxtJamPinjam.setName("TxtJamPinjam"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tblPinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPinjam.setName("tblPinjam"); // NOI18N
        tblPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPinjamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPinjam);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tanggal J.Tempo");
        jLabel12.setName("jLabel12"); // NOI18N

        TxtTglKembali.setName("TxtTglKembali"); // NOI18N
        TxtTglKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTglKembaliMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtTglKembaliMouseExited(evt);
            }
        });
        TxtTglKembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTglKembaliKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Jam");
        jLabel13.setName("jLabel13"); // NOI18N

        TxtJamKembali.setName("TxtJamKembali"); // NOI18N
        TxtJamKembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtJamKembaliKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Lama Sewa");
        jLabel14.setName("jLabel14"); // NOI18N

        TxtLamaSewa.setEditable(false);
        TxtLamaSewa.setName("TxtLamaSewa"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("DP / Uang Muka");
        jLabel15.setName("jLabel15"); // NOI18N

        TxtDP.setName("TxtDP"); // NOI18N
        TxtDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDPActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("TOTAL");
        jLabel16.setName("jLabel16"); // NOI18N

        TxtTotal.setEditable(false);
        TxtTotal.setName("TxtTotal"); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Sisa Pembayaran");
        jLabel17.setName("jLabel17"); // NOI18N

        TxtSisa.setEditable(false);
        TxtSisa.setName("TxtSisa"); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/diskette.png"))); // NOI18N
        jButton3.setText("SAVE");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/document_warning.png"))); // NOI18N
        jButton5.setText("CANCEL");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/home.png"))); // NOI18N
        jButton7.setText("EXIT");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Kode Pengembalian");
        jLabel19.setName("jLabel19"); // NOI18N

        TxtKodeKembali.setName("TxtKodeKembali"); // NOI18N

        TxtKodePeminjaman.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TxtKodePeminjaman.setName("TxtKodePeminjaman"); // NOI18N
        TxtKodePeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtKodePeminjamanMouseClicked(evt);
            }
        });
        TxtKodePeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodePeminjamanActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Denda");
        jLabel20.setName("jLabel20"); // NOI18N

        TxtDenda.setEditable(false);
        TxtDenda.setName("TxtDenda"); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Tanggal Kembali");
        jLabel21.setName("jLabel21"); // NOI18N

        TxtTglKembali1.setName("TxtTglKembali1"); // NOI18N
        TxtTglKembali1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtTglKembali1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtTglKembali1MouseExited(evt);
            }
        });
        TxtTglKembali1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTglKembali1KeyPressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Telat");
        jLabel22.setName("jLabel22"); // NOI18N

        TxtTelatHari.setName("TxtTelatHari"); // NOI18N
        TxtTelatHari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTelatHariKeyPressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("hari /");
        jLabel23.setName("jLabel23"); // NOI18N

        TxtTelatJam.setName("TxtTelatJam"); // NOI18N
        TxtTelatJam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTelatJamKeyPressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Jam");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Jam");
        jLabel18.setName("jLabel18"); // NOI18N

        TxtJamKembali3.setName("TxtJamKembali3"); // NOI18N
        TxtJamKembali3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtJamKembali3KeyPressed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("TOTAL BAYAR");
        jLabel25.setName("jLabel25"); // NOI18N

        TxtTotalBayar.setEditable(false);
        TxtTotalBayar.setName("TxtTotalBayar"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addGap(807, 807, 807))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtKodeKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtKodePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtIDPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtTglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9)
                                                .addGap(28, 28, 28)
                                                .addComponent(TxtJamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNamaPeminjam, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtJamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TxtDP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtTelatHari, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtTelatJam, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel24))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel25))))
                                    .addComponent(TxtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(TxtTglKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtJamKembali3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel19)
                        .addComponent(TxtKodeKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(TxtKodePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(TxtJamKembali3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNamaPeminjam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtIDPeminjam, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtJamPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addComponent(jLabel6)
                            .addComponent(TxtTglPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(TxtTglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(TxtJamKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(TxtLamaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(TxtTglKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(TxtDP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtTelatHari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23)
                                .addComponent(TxtTelatJam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(TxtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(TxtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(TxtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void TxtIDPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIDPeminjamActionPerformed
// TODO add your handling code here:
    int i=TxtIDPeminjam.getSelectedIndex();
        if (i==-1)
        {
            return;
        }
         try {
             String kd=(String) TxtIDPeminjam.getSelectedItem();
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql = "Select * from tblpeminjam WHERE id_peminjam=?";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd);
            ResultSet result=p.executeQuery();
            result.next();            
            
            this.TxtNamaPeminjam.setText(result.getString("nama"));           
            }catch(SQLException e){
            System.out.println(e);        
         }
}//GEN-LAST:event_TxtIDPeminjamActionPerformed

private void tblPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPinjamMouseClicked
// TODO add your handling code here:
   
}//GEN-LAST:event_tblPinjamMouseClicked

private void HapusTeks()
{
   
            
            
            this.TxtJamKembali.setText(null);
            this.TxtJamPinjam.setText(null);
            this.TxtLamaSewa.setText(null);
            this.TxtDP.setText(null);
            this.TxtSisa.setText(null);
            loadData();
}
private void TxtJamKembaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJamKembaliKeyPressed
// TODO add your handling code here:
    hitunglama();
}//GEN-LAST:event_TxtJamKembaliKeyPressed

private void TxtTglKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTglKembaliMouseClicked
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtTglKembaliMouseClicked

private void TxtTglKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTglKembaliMouseExited
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtTglKembaliMouseExited

private void TxtTglKembaliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTglKembaliKeyPressed
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtTglKembaliKeyPressed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
    String kd_kembali=this.TxtKodeKembali.getText();
    String id_pinjam=(String) this.TxtIDPeminjam.getSelectedItem();
    java.util.Date tgl_kembali=(java.util.Date) this.TxtTglKembali1.getCalendar().getTime();
    java.util.Date tgl_h_kembali=(java.util.Date) this.TxtTglKembali.getDate();
    String lama=this.TxtLamaSewa.getText();
    String jam_p=this.TxtJamPinjam.getText();
    String jam_k=this.TxtJamKembali3.getText();
    String dp=this.TxtDP.getText();
    String sisa_p=this.TxtSisa.getText();
    String denda=this.TxtDenda.getText();
    
    if( "".equals(this.TxtNamaPeminjam.getText()))
    {
       JOptionPane.showMessageDialog(this, "Lengkapi data");
    }else{
        try {
            Connection c=ClassDB.getkoneksi();
            String sql = "Insert into tblpengembalian values (?,?,?,?,?)";
            PreparedStatement p=(PreparedStatement) c.prepareStatement(sql);
            p.setString(1, kd_kembali);            
            p.setString(2, id_pinjam);
            p.setDate(3, new java.sql.Date(tgl_kembali.getTime()));            
            
            p.setString(4, denda);
          
            p.setString(5, jam_k);
          
            
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(this, "Sukses Simpan data");
            HapusTeks();
            awalmobil();
        }catch(SQLException e){
            System.out.println("Terjadi kesalahan");
        }finally{
            
            
        }
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void awalmobil()
{
    try {        
        
        
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select kd_mobil from tblpeminjamandetail";
            ResultSet r=s.executeQuery(sql);
            
            while (r.next()) {
                Connection c2=ClassDB.getkoneksi();
                
                String sql2="Update tblmobil Set status='Free' where tblmobil.kd_mobil=(Select kd_mobil from tblpeminjamandetail where tblpeminjamandetail.kd_mobil='" + r.getString("kd_mobil") + "')";
                PreparedStatement p=(PreparedStatement) c.prepareStatement(sql2);
                p.executeUpdate();
                
                

            }
            r.close();
            s.close();
                
           
                
        }catch(SQLException e) {
            System.out.println(e);
        }
}
private void TxtDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDPActionPerformed
// TODO add your handling code here:
    double l=Double.valueOf(this.TxtTotal.getText());
    double m=Double.valueOf(this.TxtDP.getText());
    DecimalFormat df = new DecimalFormat("#.##");
    double lm=Double.valueOf(l-m);
    String lms=String.valueOf(lm);
    this.TxtSisa.setText(df.format(l-m));
}//GEN-LAST:event_TxtDPActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    HapusTeks();
    loadData();
}//GEN-LAST:event_jButton5ActionPerformed

private void TxtKodePeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodePeminjamanActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_TxtKodePeminjamanActionPerformed

private void TxtKodePeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtKodePeminjamanMouseClicked
// TODO add your handling code here:
    loadData();
    try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select * from tblPeminjaman where kd_pinjam='" + this.TxtKodePeminjaman.getSelectedItem() + "'";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
                this.TxtIDPeminjam.setSelectedItem(r.getString("id_peminjam"));
            this.TxtTglPinjam.setDate(r.getDate("tgl_pinjam"));
            this.TxtTglKembali.setDate(r.getDate("tgl_hrs_kembali"));
            this.TxtJamPinjam.setText(r.getString("jam_p"));
            this.TxtJamKembali.setText(r.getString("jam_k"));
            this.TxtLamaSewa.setText(r.getString("lama_sewa"));
            this.TxtDP.setText(r.getString("dp"));
            this.TxtSisa.setText(r.getString("sisa_p"));
            
            r.close();
            s.close();
            }
            
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan " + e);
        }
    hitungtotal();
}//GEN-LAST:event_TxtKodePeminjamanMouseClicked

private void TxtTglKembali1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTglKembali1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_TxtTglKembali1MouseClicked

private void TxtTglKembali1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtTglKembali1MouseExited
// TODO add your handling code here:
}//GEN-LAST:event_TxtTglKembali1MouseExited

private void TxtTglKembali1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTglKembali1KeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_TxtTglKembali1KeyPressed

private void TxtTelatHariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelatHariKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_TxtTelatHariKeyPressed

private void TxtTelatJamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelatJamKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_TxtTelatJamKeyPressed

private void TxtJamKembali3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJamKembali3KeyPressed
// TODO add your handling code here:
  //  java.util.Date tgl1=(java.util.Date) this.TxtTglKembali.getDate();
  //  java.util.Date tgl2=(java.util.Date) this.TxtTglKembali1.getDate();
  ////  long diff=((tgl2.getTime()- tgl1.getTime())/(1000 * 60 * 60 * 24));
  //  String a=(String.valueOf(diff));
  //  this.TxtTelatHari.setText(a);
    
  //  long pp=Long.valueOf(this.TxtJamKembali.getText());
  //  long pp2=Long.valueOf(this.TxtJamKembali3.getText());
  //  long diff2=pp2-pp;
  //  String b=(String.valueOf(diff2));
  //  this.TxtTelatJam.setText(b);
    
  //  double dd=60000;
  //  double dh=(diff * dd);
 //   double dj=(diff2 * dd);
  //  double dt=dh+dj;
  //  String c=(String.valueOf(dt));
  //  this.TxtDenda.setText(c);
    DecimalFormat df = new DecimalFormat("#.##");
    int bln1=this.TxtTglKembali.getCalendar().getTime().getMonth() + 1;
    int tgl1=this.TxtTglKembali.getCalendar().getTime().getDate() ;
    int bln2=this.TxtTglKembali1.getCalendar().getTime().getMonth() + 1;
    int tgl2=this.TxtTglKembali1.getCalendar().getTime().getDate() ;
    int jam1=Integer.valueOf(this.TxtJamKembali.getText());
    int jam2=Integer.valueOf(this.TxtJamKembali3.getText());
    
    Date d1 = new GregorianCalendar(2012, bln1, tgl1, jam1, 0).getTime();
    Date d2 = new GregorianCalendar(2012, bln2, tgl2, jam2, 0).getTime();
    long diff = d2.getTime() - d1.getTime();
    long diffHours = diff / (60 * 60 * 1000);
    long diffDays = diff / (24 * 60 * 60 * 1000);
    String th=String.valueOf(diffDays);
    String th1=String.valueOf(diffHours);
    this.TxtTelatHari.setText(th);
    this.TxtTelatJam.setText(th1);
    
    
    double total_denda=60000*diffHours;
    String th3=String.valueOf(total_denda);
    this.TxtDenda.setText(df.format(60000*diffHours));
    double ss=Double.valueOf(this.TxtSisa.getText());
    double tb=ss+total_denda;
    String th4=String.valueOf(tb);
    this.TxtTotalBayar.setText(df.format(ss+total_denda));
}//GEN-LAST:event_TxtJamKembali3KeyPressed

private void hitungtotal()
{
    try {            
            Connection c=ClassDB.getkoneksi();
            Statement s= c.createStatement();
            String sql="Select sum(harga) as 'B' from tblPeminjamandetail where kd_pinjam='" + this.TxtKodePeminjaman.getSelectedItem() + "'";
            ResultSet r=s.executeQuery(sql);
            
            if(r.next())
            {
            
            double h=Double.valueOf(r.getString("B"));
            double p=Double.valueOf(h);
            
            double c2=Double.valueOf(this.TxtLamaSewa.getText());
            DecimalFormat df = new DecimalFormat("#.##");
            double c3=Double.parseDouble(df.format(p*c2));
            String l=String.valueOf(c3);
            this.TxtTotal.setText(df.format(p*c2));
            }
            
            r.close();
            s.close();
            
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan::" + e);
        }
}

private void updatemobil(String kdmobil)
{
    String sql1="Update tblmobil Set status='Loan' where kd_mobil=?";
    try {        
    Connection c=ClassDB.getkoneksi();            
            PreparedStatement st=(PreparedStatement) c.prepareStatement(sql1);
            st.setString(1, kdmobil);            
            
            st.executeUpdate();
            st.close();
            
    }catch(SQLException e) {
        System.out.println(e);
    }
}

private void hitunglama()
{       
    //Date d1 = new GregorianCalendar(this.TxtTglPinjam.getDate().getYear(), this.TxtTglPinjam.getDate().getMonth(), this.TxtTglPinjam.getDate().getDay(), 22, 59).getTime();
   // Date d2 = new GregorianCalendar(2012, 6, 3, 0, 59).getTime();
    //Date today = new Date();
    //long diff = d2.getTime() - d1.getTime();
   // JOptionPane.showMessageDialog(this, (diff / (1000 * 60 * 60 )));
    java.util.Date tgl1=(java.util.Date) this.TxtTglPinjam.getDate();
    java.util.Date tgl2=(java.util.Date) this.TxtTglKembali.getDate();
    long diff=((tgl2.getTime()- tgl1.getTime())/(1000 * 60 * 60 * 24));
    String a=(String.valueOf(diff));
    this.TxtLamaSewa.setText(a);
    hitungtotal();
    
    
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtDP;
    private javax.swing.JTextField TxtDenda;
    private javax.swing.JComboBox TxtIDPeminjam;
    private javax.swing.JTextField TxtJamKembali;
    private javax.swing.JTextField TxtJamKembali3;
    private javax.swing.JTextField TxtJamPinjam;
    private javax.swing.JTextField TxtKodeKembali;
    private javax.swing.JComboBox TxtKodePeminjaman;
    private javax.swing.JTextField TxtLamaSewa;
    private javax.swing.JTextField TxtNamaPeminjam;
    private javax.swing.JTextField TxtSisa;
    private javax.swing.JTextField TxtTelatHari;
    private javax.swing.JTextField TxtTelatJam;
    private com.toedter.calendar.JDateChooser TxtTglKembali;
    private com.toedter.calendar.JDateChooser TxtTglKembali1;
    private com.toedter.calendar.JDateChooser TxtTglPinjam;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JTextField TxtTotalBayar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPinjam;
    // End of variables declaration//GEN-END:variables
}
